{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-07-11 21:36:10.755137: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
      "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n"
     ]
    }
   ],
   "source": [
    "# Random Forest (RF) malware experiment\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from tensorflow.keras.utils import pad_sequences\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.feature_selection import SelectFromModel\n",
    "from sklearn.model_selection import train_test_split\n",
    "import os\n",
    "from sklearn.metrics import confusion_matrix\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sklearn.model_selection import KFold\n",
    "from sklearn.metrics import confusion_matrix\n",
    "from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score\n",
    "import datetime\n",
    "\n",
    "reverse_mal_lookup = {5: 'Trojan', 1: 'Backdoor', 2: 'Downloader', 7: 'Worms', 4: 'Spyware', 0: 'Adware', 3: 'Dropper', 6: 'Virus'}\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "def write_classification_metrics_to_file(y_values, predictions, notes):\n",
    "    # Calculate metrics for each class separately\n",
    "    accuracy = accuracy_score(y_values, predictions)\n",
    "    precision = precision_score(y_values, predictions, average=None)\n",
    "    recall = recall_score(y_values, predictions, average=None)\n",
    "    f1score = f1_score(y_values, predictions, average=None)\n",
    "\n",
    "    # Open the file in append mode\n",
    "    with open(\"reports/classification_metrics.txt\", \"a\") as file:\n",
    "        # Add timestamp to each line\n",
    "        timestamp = datetime.datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n",
    "        \n",
    "        # Write the metrics with timestamp to the file\n",
    "        file.write(f\"\\n\\nTimestamp: {timestamp}-{notes}\\n\")\n",
    "        file.write(f\"Accuracy: {accuracy}\\n\\n\")\n",
    "\n",
    "        for i, family_score in enumerate(precision):\n",
    "            file.write(f\"{reverse_mal_lookup[i]}'s Precision: {precision[i]}\\n\")\n",
    "        file.write(f\"\\n\")\n",
    "\n",
    "        for i, family_score in enumerate(recall):\n",
    "            file.write(f\"{reverse_mal_lookup[i]}'s recall: {recall[i]}\\n\")\n",
    "        file.write(f\"\\n\")\n",
    "\n",
    "        for i, family_score in enumerate(f1score):\n",
    "            file.write(f\"{reverse_mal_lookup[i]}'s f1score: {f1score[i]}\\n\")\n",
    "        file.write(f\"\\n\")\n",
    "\n",
    "\n",
    "    # Print the metrics\n",
    "    print(\"Accuracy:\", accuracy)\n",
    "    print(\"Precision:\", precision)\n",
    "    print(\"Recall:\", recall)\n",
    "    print(\"F1-score:\\n\", f1score)\n",
    "    print(lookup)\n",
    "\n",
    "# load data from api lists\n",
    "# data consist of the families Trojan, Backdoor, Downloader, Worms, Spyware, Adware, Dropper, Virus\n",
    "def read_api_labels():\n",
    "    df = pd.read_csv(\"data/api_labels.txt\", header=None)\n",
    "    print(\"label data shape: \" + str(df.shape))\n",
    "    \n",
    "    # Convert values to integers\n",
    "    df_ints = df.apply(lambda x: x.astype('category').cat.codes)\n",
    "    \n",
    "    # Create an empty hashmap\n",
    "    hashmap = {}\n",
    "    \n",
    "    # Iterate through the DataFrame\n",
    "    for index, row in df.iterrows():\n",
    "        key = row[0]  # Assuming the string column is at index 0\n",
    "        value = df_ints.iloc[index][0]  # Assuming the integer column is at index 0\n",
    "        hashmap[key] = value\n",
    "        \n",
    "    return df_ints, hashmap\n",
    "\n",
    "\n",
    "def read_call_data():\n",
    "    before_size = []\n",
    "    after_size = []\n",
    "\n",
    "    df = pd.read_csv(\n",
    "        \"data/api_calls.txt\", delimiter=' ', header=None)\n",
    "    print(\"call data shape: \" + str(df.shape))\n",
    "    D = df.values\n",
    "    ds_tmp = D[:, 0].tolist()\n",
    "    ds = []\n",
    "    for v in ds_tmp:\n",
    "        ds_int_strings = [int(i) for i in v.split(',')]\n",
    "        # removing the line below due to it being too cpu costly\n",
    "        #ds_int_strings_compressed = triple_pass_redundant_sequence_removal(ds_int_strings)\n",
    "        ds.append(ds_int_strings)\n",
    "    return ds\n",
    "\n",
    "# Create a matrix of shape (7107,342), and for each sample fill out the matrix so each api call is at a specific index and then go through and \n",
    "# increment each time you iterate across that api \n",
    "def make_call_frequency_count(calls):\n",
    "    samples_freq_count = np.zeros((7107, 342))\n",
    "\n",
    "    sample_count = 0\n",
    "    for i, arr in enumerate(calls):\n",
    "        samples_freq_count[i, arr] += 1\n",
    "\n",
    "    print(samples_freq_count.shape)\n",
    "    return samples_freq_count\n",
    "\n",
    "def visualize_confusion_matrix(y_true, predictions):\n",
    "    cm = confusion_matrix(y_true, predictions)\n",
    "    sns.heatmap(cm, annot=True, fmt=\"d\")\n",
    "    plt.xlabel(\"Predicted Labels\")\n",
    "    plt.ylabel(\"True Labels\")\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "label data shape: (7107, 1)\n",
      "call data shape: (7107, 1)\n",
      "(7107, 342)\n"
     ]
    }
   ],
   "source": [
    "# data frames. call data is a 2d list and api is a 2d df\n",
    "labels, lookup = read_api_labels()\n",
    "answers = labels[0] \n",
    "samples_freq_count = make_call_frequency_count(read_call_data())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/sklearn/base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return fit_method(estimator, *args, **kwargs)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Selected Features: [  2  10  28  34  38  39  40  42  43  44  46  47  48  49  50  51  52  54\n",
      "  55  56  58  62  63  64  66  67  69  71  72  73  74  75  77  78  79  80\n",
      "  88  89  91  92  94  95  96  99 102 103 104 105 106 107 113 117 122 130\n",
      " 133 135 138 139 142 158 160 161 162 163 164 165 166 167 170 173 175 176\n",
      " 177 178 179 180 181 182 185 186 187 190 192 195 197 199 200 203 204 205\n",
      " 206 207 210 211 213 215 219 220 221 222 223 225 226 227 228 229 230 231\n",
      " 232 233 235 236 237 238 239 240 243 244 248 249 250 252 257 258 259 260\n",
      " 261 262 263 268 270 271 272 273 274 278 280 281 284 285 286 287 288 289\n",
      " 290 291 292 293 294 295 302 303 307 308 309 310 311 312 315 316 317 318\n",
      " 319 321 322 323 324 325 326 327 328 329 330 331]\n"
     ]
    }
   ],
   "source": [
    "# feature selection\n",
    "random_forest = RandomForestClassifier(n_estimators=1000, )\n",
    "random_forest.fit(samples_freq_count, labels)\n",
    "feature_importance = random_forest.feature_importances_\n",
    "selector = SelectFromModel(random_forest, threshold=0.001)  # Adjust the threshold as needed\n",
    "selected_call_dataset = selector.transform(samples_freq_count)\n",
    "selected_features_indexes = selector.get_support(indices=True)\n",
    "print(\"Selected Features:\", selected_features_indexes)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fold 1: Accuracy = 0.35443037974683544\n",
      "Fold 2: Accuracy = 0.6223628691983122\n",
      "Fold 3: Accuracy = 0.6720619282195637\n",
      "Fold 4: Accuracy = 0.5728360309641097\n",
      "Fold 5: Accuracy = 0.6488388458831809\n",
      "Mean Accuracy: 0.5741060108024004\n",
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "  File \"/var/folders/w_/wq7n_2h911l66llfcg9jjxvc0000gn/T/ipykernel_41188/1628129438.py\", line 35, in <module>\n",
      "    visualize_confusion_matrix(true_labels,predicted_labels)\n",
      "  File \"/var/folders/w_/wq7n_2h911l66llfcg9jjxvc0000gn/T/ipykernel_41188/752693317.py\", line 89, in visualize_confusion_matrix\n",
      "    sns.heatmap(cm, annot=True, fmt=\"d\")\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/seaborn/matrix.py\", line 456, in heatmap\n",
      "    ax = plt.gca()\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/matplotlib/pyplot.py\", line 2309, in gca\n",
      "    return gcf().gca()\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/matplotlib/pyplot.py\", line 906, in gcf\n",
      "    return figure()\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/matplotlib/_api/deprecation.py\", line 454, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/matplotlib/pyplot.py\", line 840, in figure\n",
      "    manager = new_figure_manager(\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/matplotlib/pyplot.py\", line 383, in new_figure_manager\n",
      "    _warn_if_gui_out_of_main_thread()\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/matplotlib/pyplot.py\", line 361, in _warn_if_gui_out_of_main_thread\n",
      "    if _get_required_interactive_framework(_get_backend_mod()):\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/matplotlib/pyplot.py\", line 208, in _get_backend_mod\n",
      "    switch_backend(rcParams._get(\"backend\"))\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/matplotlib/pyplot.py\", line 271, in switch_backend\n",
      "    backend_mod = importlib.import_module(\n",
      "  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 972, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 984, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'matplotlib_inline'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2105, in showtraceback\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1428, in structured_traceback\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1319, in structured_traceback\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1172, in structured_traceback\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1087, in format_exception_as_a_whole\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 969, in format_record\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 792, in lines\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/stack_data/utils.py\", line 144, in cached_property_wrapper\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/stack_data/core.py\", line 734, in lines\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/stack_data/utils.py\", line 144, in cached_property_wrapper\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/stack_data/core.py\", line 677, in included_pieces\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/stack_data/utils.py\", line 144, in cached_property_wrapper\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/stack_data/core.py\", line 614, in scope_pieces\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/stack_data/core.py\", line 178, in line_range\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/executing/executing.py\", line 428, in asttext\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/asttokens/asttokens.py\", line 307, in __init__\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/asttokens/asttokens.py\", line 44, in __init__\n",
      "AttributeError: module 'six' has no attribute 'ensure_text'\n"
     ]
    }
   ],
   "source": [
    "# write notes for metrics\n",
    "notes = \"running with 5-fold cross validation and selected features with 1000 RF estimators\"\n",
    "\n",
    "# Perform 5-fold cross-validation\n",
    "kf = KFold(n_splits=5)\n",
    "scores = []\n",
    "\n",
    "# Define empty lists for storing predicted labels and true labels\n",
    "predicted_labels = []\n",
    "true_labels = []\n",
    "\n",
    "# train using RF\n",
    "for fold, (train_indexes, test_indexes) in enumerate(kf.split(selected_call_dataset)):\n",
    "    random_forest = RandomForestClassifier(n_estimators=1000)\n",
    "    \n",
    "    # Fit the model on training data and make predictions on test data\n",
    "    random_forest.fit(selected_call_dataset[train_indexes], answers[train_indexes])\n",
    "    predictions = random_forest.predict(selected_call_dataset[test_indexes])\n",
    "\n",
    "    # Store the predicted labels and true labels\n",
    "    predicted_labels.extend(predictions)\n",
    "    true_labels.extend(answers[test_indexes])\n",
    "\n",
    "    # Calculate accuracy for the current fold\n",
    "    accuracy = accuracy_score(answers[test_indexes], predictions)\n",
    "    scores.append(accuracy)\n",
    "\n",
    "    print(f\"Fold {fold + 1}: Accuracy = {accuracy}\")\n",
    "\n",
    "# Calculate and print the mean accuracy across all folds\n",
    "mean_accuracy = np.mean(scores)\n",
    "print(f\"Mean Accuracy: {mean_accuracy}\")\n",
    "\n",
    "# Calculate and print the confusion matrix\n",
    "visualize_confusion_matrix(true_labels,predicted_labels)\n",
    "\n",
    "# print the metrics to file\n",
    "write_classification_metrics_to_file(true_labels, predicted_labels, notes)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "# TODO Update to filter the malware samples dataset by filtering on the malware family type\n",
    "\n",
    "# plotting out the values grouped by key to better show a distribution of the values in the dataset\n",
    "def plot_malware_sample_values(family):\n",
    "    aggregated_values = {}\n",
    "\n",
    "    for column in df.columns:\n",
    "        aggregated_values[column] = df[column].sum()\n",
    "\n",
    "    x = list(aggregated_values.keys())\n",
    "    y = list(aggregated_values.values())\n",
    "\n",
    "    plt.bar(x, y)\n",
    "    plt.xlabel(\"Keys\")\n",
    "    plt.ylabel(\"Values\")\n",
    "    plt.title(\"Plot of Dictionary\")\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "  File \"/var/folders/w_/wq7n_2h911l66llfcg9jjxvc0000gn/T/ipykernel_41188/2238068792.py\", line 1, in <module>\n",
      "    plot_malware_sample_values(5)\n",
      "  File \"/var/folders/w_/wq7n_2h911l66llfcg9jjxvc0000gn/T/ipykernel_41188/2973571924.py\", line 7, in plot_malware_sample_values\n",
      "    for column in df.columns:\n",
      "NameError: name 'df' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2105, in showtraceback\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1428, in structured_traceback\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1319, in structured_traceback\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1172, in structured_traceback\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1087, in format_exception_as_a_whole\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 969, in format_record\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 792, in lines\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/stack_data/utils.py\", line 144, in cached_property_wrapper\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/stack_data/core.py\", line 734, in lines\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/stack_data/utils.py\", line 144, in cached_property_wrapper\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/stack_data/core.py\", line 677, in included_pieces\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/stack_data/utils.py\", line 144, in cached_property_wrapper\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/stack_data/core.py\", line 614, in scope_pieces\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/stack_data/core.py\", line 178, in line_range\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/executing/executing.py\", line 428, in asttext\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/asttokens/asttokens.py\", line 307, in __init__\n",
      "  File \"/Users/eric_howard/MyCode/rf_malware_classification/venv/lib/python3.9/site-packages/asttokens/asttokens.py\", line 44, in __init__\n",
      "AttributeError: module 'six' has no attribute 'ensure_text'\n"
     ]
    }
   ],
   "source": [
    "plot_malware_sample_values(5)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "rf_mal_env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.6"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
